FROM raghukul01/lamp:version1

ADD index.php /var/www/example.com/public_html/


# docker run -it -p 8080:80 bhavishya/mysql
# Run inside container 
# `service apache2 start`
# `service mysql start` 
